### ISSUE TITLE
changing the readme

### ISSUE THREAD

**Issue by chiaramoruzzi** [DataAccess2020/CE1_Moruzzi_Taddei#4]
Do you want to update the Readme file today or should we do it later?
@Federico00taddei

**Comment by Federico00taddei** [comment]
Dear @chiaramoruzzi, fellow collaborator, I think that it would be a wonderful and smart idea to do it today, before the dinner pause.
Cordially.
Federico

**Comment by chiaramoruzzi** [comment]
It's ok but we should try to make some kind of list with all the folders; I think it would be more intuitive

**Comment by Federico00taddei** [comment]
Sorry @chiaramoruzzi , I'm hungry and I didn't notice. Thanks!
Now it's correct :)
